version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_web
    command: gunicorn _homework.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/project                # 루트 대신 /app에 마운트
      - static_volume:/staticfiles
      -  media_volume:/project/media  # media 볼륨 추가
    working_dir: /project         # 작업 디렉토리를 /app으로 설정
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=_homework.settings

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/project/media  # media 볼륨 공유
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
